package com.example.protobufferstest;

import com.example.protobufferstest.GRPCautogenerated.com.example.grpc.generated.GrpcOrder;
import com.example.protobufferstest.Service.OrderServiceImpl;
import com.example.protobufferstest.Service.OrderServiceLogic;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class ProtoBuffersTestApplication {

    public static void main(String[] args) {
        SpringApplication.run(ProtoBuffersTestApplication.class, args);
    }

    @Bean
    public CommandLineRunner loadData(OrderServiceLogic orderServiceLogic) {
        return args -> {
            long orderCount = orderServiceLogic.getAllOrdersCount();

            if (orderCount == 0) {
                GrpcOrder order1 = GrpcOrder.newBuilder()
                        .setBookingId(1L)
                        .setServiceProviderId(1L)
                        .setServiceId(101L)
                        .setTotalAmount(150.0)
                        .build();

                GrpcOrder order2 = GrpcOrder.newBuilder()
                        .setBookingId(2L)
                        .setServiceProviderId(2L)
                        .setServiceId(102L)
                        .setTotalAmount(200.0)
                        .build();

                GrpcOrder order3 = GrpcOrder.newBuilder()
                        .setBookingId(3L)
                        .setServiceProviderId(3L)
                        .setServiceId(103L)
                        .setTotalAmount(300.0)
                        .build();

                orderServiceLogic.createOrder(order1);
                orderServiceLogic.createOrder(order2);
                orderServiceLogic.createOrder(order3);

                System.out.println("Placeholder orders have been added to the database.");
            } else {
                System.out.println("Orders already exist, skipping placeholder data insertion.");
            }
        };
    }
}
